source "https://rubygems.org"

gem "jekyll", "4.3.3"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.10.1"
  gem 'jekyll-tagging', "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
end
